name: Trigger auto deployment for containerapps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]

  # Allow manually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push Images
        run: |        
          docker build --file DemoActor/Dockerfile -t ${{ secrets.REGISTRY_USERNAME }}/demoactor:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_USERNAME }}/demoactor:${{ github.sha }}
          docker build --file DemoActorApi/Dockerfile -t ${{ secrets.REGISTRY_USERNAME }}/demoactorapi:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_USERNAME }}/demoactorapi:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |                        
            az deployment group create -g ${{ secrets.CA_RG }}  --template-file templates/appresources.bicep --parameters environmentName=${{ secrets.CA_ENV }} imageNameActor=${{ secrets.REGISTRY_USERNAME }}/demoactor:${{ github.sha }} imageNameActorApi=${{ secrets.REGISTRY_USERNAME }}/demoactorapi:${{ github.sha }}